const Blockchain = require('./blockchain')
const bitcoin = new Blockchain()
bitcoin.createNewBlock(2334, 'ADFAFSDFSADSGGSADA', 'afdliuklaidfhasdlkfh')
bitcoin.createTransaction(100, 'HANBITOASDFASDFIBH', 'DAVINAAGAHYHADFASDJFDSA')
bitcoin.createNewBlock(123124, 'ADSFBHASDHFASDF', 'asdfadsfwetgsagas')
bitcoin.createTransaction(5, 'HANBITOASDFASDFIBH', 'DAVINAAGAHYHADFASDJFDSA')
bitcoin.createTransaction(200, 'HANBITOASDFASDFIBH', 'DAVINAAGAHYHADFASDJFDSA')
bitcoin.createTransaction(500, 'HANBITOASDFASDFIBH', 'DAVINAAGAHYHADFASDJFDSA')
bitcoin.createNewBlock(12313, 'SAVEPENDINGTRANS', 'ASDFASDFSADFDSAFA')
console.log(bitcoin.chain[2])